export const mockCommunityData = [
  {
    id: 1,
    rut: "11.111.111-1",
    nombre: "Ana González",
    territorio: "Araucanía",
    tipo: "Emprendedor",
    programa: "Balloon Impulsa 2023",
    email: "ana.gonzalez@example.com",
    telefono: "+56987654321",
    fecha_registro: "2023-01-15",
  },
  {
    id: 2,
    rut: "22.222.222-2",
    nombre: "Carlos Fuentes",
    territorio: "Biobío",
    tipo: "Líder Comunitario",
    programa: "Líderes en Acción 2022",
    email: "carlos.fuentes@example.com",
    telefono: "+56912345678",
    fecha_registro: "2022-05-20",
  },
  {
    id: 3,
    rut: "33.333.333-3",
    nombre: "Beatriz Parra",
    territorio: "Los Lagos",
    tipo: "Ambos",
    programa: "Balloon Impulsa 2023",
    email: "beatriz.parra@example.com",
    telefono: "+56955556666",
    fecha_registro: "2023-02-10",
  },
  {
    id: 4,
    rut: "44.444.444-4",
    nombre: "David Soto",
    territorio: "Araucanía",
    tipo: "Persona Pública",
    programa: "N/A",
    email: "david.soto@example.com",
    telefono: "+56977778888",
    fecha_registro: "2021-11-30",
  },
  {
    id: 5,
    rut: "55.555.555-5",
    nombre: "Elena Castillo",
    territorio: "Biobío",
    tipo: "Emprendedor",
    programa: "Emprende Rural 2023",
    email: "elena.castillo@example.com",
    telefono: "+56933334444",
    fecha_registro: "2023-03-05",
  },
  {
    id: 6,
    rut: "66.666.666-6",
    nombre: "Felipe Rojas",
    territorio: "Los Ríos",
    tipo: "Emprendedor",
    programa: "Balloon Impulsa 2023",
    email: "felipe.rojas@example.com",
    telefono: "+56911112222",
    fecha_registro: "2023-01-25",
  },
  {
    id: 7,
    rut: "77.777.777-7",
    nombre: "Gabriela Medina",
    territorio: "Araucanía",
    tipo: "Líder Comunitario",
    programa: "Líderes en Acción 2023",
    email: "gabriela.medina@example.com",
    telefono: "+56998765432",
    fecha_registro: "2023-04-12",
  },
];

export const mockDataDictionary = [
  {
    id: 1,
    columna: "rut",
    tipo_dato: "String",
    validacion: "^\\d{1,2}\\.\\d{3}\\.\\d{3}-[\\dkK]$",
    requerido: true,
    descripcion: "RUT en formato chileno.",
  },
  {
    id: 2,
    columna: "nombre",
    tipo_dato: "String",
    longitud_max: 100,
    requerido: true,
    descripcion: "Nombre completo.",
  },
  {
    id: 3,
    columna: "territorio",
    tipo_dato: "Lista",
    opciones: ["Araucanía", "Biobío", "Los Lagos", "Los Ríos"],
    requerido: true,
    descripcion: "Territorio de pertenencia.",
  },
  {
    id: 4,
    columna: "tipo",
    tipo_dato: "Lista",
    opciones: ["Emprendedor", "Líder Comunitario", "Ambos", "Persona Pública"],
    requerido: true,
    descripcion: "Clasificación de la persona.",
  },
  {
    id: 5,
    columna: "email",
    tipo_dato: "String",
    validacion: "^\\S+@\\S+\\.\\S+$",
    requerido: false,
    descripcion: "Correo electrónico válido.",
  },
];

export const mockUploadHistory = [
  {
    id: 1,
    nombre_archivo: "emprendedores_araucania_q1.csv",
    fecha_carga: "2024-05-10 10:30",
    usuario: "admin@balloonlatam.com",
    estado: "Completado",
    registros: 150,
  },
  {
    id: 2,
    nombre_archivo: "lideres_biobio.csv",
    fecha_carga: "2024-05-12 15:00",
    usuario: "admin@balloonlatam.com",
    estado: "Completado",
    registros: 45,
  },
  {
    id: 3,
    nombre_archivo: "nuevos_ingresos.xlsx",
    fecha_carga: "2024-05-15 09:00",
    usuario: "user@balloonlatam.com",
    estado: "Fallido",
    registros: 0,
    error: 'Columna "rut" no encontrada.',
  },
];

export const mockChangeHistory = [
  {
    id: 1,
    fecha: "2024-05-14 11:00",
    usuario: "admin@balloonlatam.com",
    resumen: 'Actualizó el territorio de Ana González a "Biobío".',
  },
  {
    id: 2,
    fecha: "2024-05-13 18:20",
    usuario: "admin@balloonlatam.com",
    resumen: "Creó 45 nuevos registros desde el archivo lideres_biobio.csv.",
  },
  {
    id: 3,
    fecha: "2024-05-12 09:45",
    usuario: "user@balloonlatam.com",
    resumen: "Actualizó el teléfono de David Soto.",
  },
];

export const mockDownloadHistory = [
  {
    id: 1,
    fecha: "2024-05-15 12:00",
    usuario: "admin@balloonlatam.com",
    filtros: "Territorio: Araucanía, Tipo: Emprendedor",
  },
  {
    id: 2,
    fecha: "2024-05-14 16:30",
    usuario: "user@balloonlatam.com",
    filtros: "Programa: Balloon Impulsa 2023",
  },
];

export const mockUsers = [
  {
    id: 1,
    nombre: "Admin General",
    email: "admin@balloonlatam.com",
    rol: "Administrador",
  },
  {
    id: 2,
    nombre: "Catalina Flores",
    email: "user@balloonlatam.com",
    rol: "Gestor de Datos",
  },
];
